<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employetable [
<!ELEMENT employetable (employ)*>
<!ELEMENT employ (id,name,salary,date,position)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT position (#PCDATA)>
]>


<employetable>
<employ>
<id>
10234
</id>
<name>
Salman
</name>
<salary>
5000
</salary>
<date>
2-2-2015
</date>
<position>
Manager
</position>
</employ>


<employ>
<id>
10235
</id>
<name>
Ibrahim
</name>
<salary>
20000
</salary>
<date>
2-2-1990
</date>
<position>
CEO
</position>
</employ>


<employ>
<id>
10236
</id>
<name>
asim
</name>
<salary>
5000
</salary>
<date>
4-4-2017
</date>
<position>
Manager
</position>
</employ>


<employ>
<id>
10237
</id>
<name>
Ghazanfar
</name>
<salary>
5000
</salary>
<date>
8-10-2015
</date>
<position>
Manager
</position>
</employ>


<employ>
<id>
10238
</id>
<name>
Saima
</name>
<salary>
10000
</salary>
<date>
2-2-2015
</date>
<position>
MD
</position>
</employ>
</employetable>